[package]
name = "bvr"
description = "Chew through logs."
categories = ["command-line-utilities"]
authors = ["An Tran <antranprm@gmail.com>"]
version = "0.0.1"
edition = "2021"
license = "MIT"
keywords = ["cli", "pager"]
homepage = "https://github.com/Avarel/bvr"
repository = "https://github.com/Avarel/bvr"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["cargo", "derive"] }
crossterm = "0.27"
memchr = "2.6"
memmap2 = "0.9"
quick_cache = "0.4"
ratatui = "0.24"
tempfile = "3.8"
tokio = { version = "1", features = ["sync", "rt-multi-thread", "fs"] }
grep = "0.2"

[dev-dependencies]
rand = "0.8"
time = "0.3"

[profile.release]
debug = true
