[package]
name = "bvr"
description = "Chew through logs."
categories = ["command-line-utilities"]
authors = ["An Tran <antranprm@gmail.com>"]
version = "0.0.2"
edition = "2021"
license = "MIT"
keywords = ["cli", "pager"]
homepage = "https://github.com/Avarel/bvr"
repository = "https://github.com/Avarel/bvr"

exclude = [
  "HomebrewFormula",
  "/.github/",
  "/ci/",
  "/pkg/",
  "/benchsuite/",
  "/scripts/",
]

[[bin]]
bench = false
path = "crates/core/main.rs"
name = "bvr"

[workspace]
members = ["crates/file"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["cargo", "derive"] }
crossterm = "0.27"
ratatui = "0.24"
tempfile = "3.8"
tokio = { version = "1", features = ["sync", "rt-multi-thread", "fs"] }
grep = "0.2"
bvr-file = { path = "crates/file" }

[dev-dependencies]
rand = "0.8"
time = "0.3"

[profile.release]
debug = true
