[package]
name = "bvr"
description = "Chew through logs."
categories = ["command-line-utilities"]
authors = ["An Tran <antranprm@gmail.com>"]
version = "0.0.2"
edition = "2021"
license = "MIT"
keywords = ["cli", "pager"]
homepage = "https://github.com/Avarel/bvr"
repository = "https://github.com/Avarel/bvr"
readme = "README.md"

exclude = [
  "HomebrewFormula",
  "/.github/",
  "/ci/",
  "/pkg/",
  "/benchsuite/",
  "/scripts/",
]

[[bin]]
bench = false
path = "crates/cli/main.rs"
name = "bvr"

[workspace]
members = ["crates/core"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["cargo", "derive"] }
crossterm = { version = "0.27", features = ["use-dev-tty"] }
ratatui = "0.24"
tokio = { version = "1", features = ["sync", "rt-multi-thread", "fs", "io-util", "io-std"] }
bvr-core = { path = "crates/core" }
libc = "0.2.150"

[dev-dependencies]
rand = { version = "0.8", features = ["small_rng"] }
time = "0.3"

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1